import type { Brand, Car, CategoryDef, Story } from "./types";

export const categories: CategoryDef[] = [
  { id: "supercars", label: "Supercars", line: "Built to make your heart race." },
  { id: "sports", label: "Sports Cars", line: "Precision, distilled into every corner." },
  { id: "luxury", label: "Luxury", line: "Comfort that still knows how to move." },
  { id: "electric", label: "Electric", line: "Silent power. Instant everything." },
  { id: "suv", label: "SUV", line: "No road is off-limits." },
  { id: "performance", label: "Performance", line: "Everyday, until it isn't." },
  { id: "classics", label: "Classics", line: "The shapes that never stopped turning heads." },
];

export const cars: Car[] = [
  {
    slug: "porsche-911-gt3-rs",
    brand: "Porsche",
    model: "911 GT3 RS",
    category: "supercars",
    year: 2024,
    priceFrom: 1150000,
    horsepower: 525,
    torqueNm: 465,
    zeroToHundred: 3.2,
    topSpeed: 296,
    weightKg: 1450,
    fuelType: "Petrol",
    transmission: "7-speed PDK",
    drive: "RWD",
    environment: "track",
    silhouette: "supercar",
    hue: 84,
    tagline: "A race car with a license plate.",
    description:
      "The GT3 RS borrows its front fenders and cooling ducts almost wholesale from the Cup racer. Every wing, vent, and louver earns its place — the rear wing alone can generate more downforce than the car weighs at speed.",
    interiorNote:
      "Bare carbon door panels, a fixed racing seat, and a rev counter that means it. Nothing in here is asking to be comfortable — it's asking to be fast.",
    feelings: ["speed", "attention"],
    related: ["lamborghini-huracan-sto", "mclaren-artura", "audi-r8-v10"],
  },
  {
    slug: "ferrari-sf90-stradale",
    brand: "Ferrari",
    model: "SF90 Stradale",
    category: "supercars",
    year: 2024,
    priceFrom: 1780000,
    horsepower: 986,
    torqueNm: 800,
    zeroToHundred: 2.5,
    topSpeed: 340,
    weightKg: 1570,
    fuelType: "Hybrid",
    transmission: "8-speed DCT",
    drive: "AWD",
    environment: "studio",
    silhouette: "supercar",
    hue: 4,
    tagline: "Maranello's first plug-in hybrid supercar.",
    description:
      "Three electric motors and a twin-turbo V8 combine for the most power a road-going Ferrari has ever produced. In full electric mode it can glide through a quiet street on battery alone — then remember what it actually is.",
    interiorNote:
      "A driver-focused cockpit borrowed from single-seater racing, with a fully digital dash and steering-wheel controls that keep both hands on the wheel at all times.",
    feelings: ["speed", "technology", "attention"],
    related: ["mclaren-artura", "lamborghini-huracan-sto", "bugatti-chiron-super-sport"],
  },
  {
    slug: "lamborghini-huracan-sto",
    brand: "Lamborghini",
    model: "Huracán STO",
    category: "supercars",
    year: 2023,
    priceFrom: 1050000,
    horsepower: 640,
    torqueNm: 565,
    zeroToHundred: 3.0,
    topSpeed: 310,
    weightKg: 1339,
    fuelType: "Petrol",
    transmission: "7-speed DCT",
    drive: "RWD",
    environment: "track",
    silhouette: "supercar",
    hue: 52,
    tagline: "Super Trofeo Omologata. Race car, homologated for the road.",
    description:
      "A one-piece front clamshell, a naturally-aspirated V10 that revs to 8,500 rpm, and aerodynamics developed directly from Lamborghini's GT3 racing program. There is no hybrid assistance here — just displacement and nerve.",
    interiorNote:
      "Alcantara, exposed carbon weave, and a start button under a fighter-jet-style flip cover. The infotainment screen is angled toward the driver like everything else in the cabin.",
    feelings: ["speed", "attention"],
    related: ["ferrari-sf90-stradale", "porsche-911-gt3-rs", "mclaren-artura"],
  },
  {
    slug: "mclaren-artura",
    brand: "McLaren",
    model: "Artura",
    category: "supercars",
    year: 2024,
    priceFrom: 980000,
    horsepower: 690,
    torqueNm: 720,
    zeroToHundred: 3.0,
    topSpeed: 330,
    weightKg: 1498,
    fuelType: "Hybrid",
    transmission: "8-speed DCT",
    drive: "RWD",
    environment: "studio",
    silhouette: "supercar",
    hue: 24,
    tagline: "McLaren's first series-production hybrid, built from a clean sheet.",
    description:
      "A new carbon architecture, a compact twin-turbo V6, and an axial-flux electric motor small enough to fit inside the engine bay. It's the most technologically dense car McLaren has ever put a number plate on.",
    interiorNote:
      "A driver-first cabin with steering-wheel-mounted controls and a folding digital display, so the road ahead never has to compete for attention.",
    feelings: ["speed", "technology"],
    related: ["porsche-911-gt3-rs", "audi-r8-v10", "lamborghini-huracan-sto"],
  },
  {
    slug: "audi-r8-v10",
    brand: "Audi",
    model: "R8 V10 Performance",
    category: "supercars",
    year: 2023,
    priceFrom: 890000,
    horsepower: 602,
    torqueNm: 560,
    zeroToHundred: 3.2,
    topSpeed: 331,
    weightKg: 1595,
    fuelType: "Petrol",
    transmission: "7-speed DCT",
    drive: "AWD",
    environment: "night-city",
    silhouette: "supercar",
    hue: 200,
    tagline: "The everyday supercar. The last of its kind.",
    description:
      "The final naturally-aspirated V10 road car Audi will build. Quattro all-wheel drive makes it the supercar you can drive in the rain without flinching — and the one that still sounds like nothing else at 8,700 rpm.",
    interiorNote:
      "The Virtual Cockpit puts every gauge in front of the driver instead of the center stack — a layout Audi pioneered here before it spread across the whole lineup.",
    feelings: ["speed", "attention"],
    related: ["porsche-911-gt3-rs", "mclaren-artura", "nissan-gt-r-nismo"],
  },
  {
    slug: "bugatti-chiron-super-sport",
    brand: "Bugatti",
    model: "Chiron Super Sport",
    category: "supercars",
    year: 2023,
    priceFrom: 14200000,
    horsepower: 1600,
    torqueNm: 1600,
    zeroToHundred: 2.4,
    topSpeed: 440,
    weightKg: 1995,
    fuelType: "Petrol",
    transmission: "7-speed DCT",
    drive: "AWD",
    environment: "desert",
    silhouette: "supercar",
    hue: 210,
    tagline: "An 8-liter, quad-turbo W16. Built for one number: 440.",
    description:
      "Longer, lower, and more slippery than the standard Chiron, purpose-built to chase top speed rather than lap times. Fewer than sixty will ever be built — each one a rolling argument for what an internal-combustion engine can still do.",
    interiorNote:
      "Hand-finished leather and milled aluminum switchgear, with a top-speed key that unlocks the car's full 440 km/h mode only when the driver asks for it.",
    feelings: ["speed", "attention", "future"],
    related: ["ferrari-sf90-stradale", "lamborghini-huracan-sto", "rolls-royce-spectre"],
  },
  {
    slug: "ferrari-roma",
    brand: "Ferrari",
    model: "Roma",
    category: "sports",
    year: 2024,
    priceFrom: 920000,
    horsepower: 620,
    torqueNm: 760,
    zeroToHundred: 3.4,
    topSpeed: 320,
    weightKg: 1570,
    fuelType: "Petrol",
    transmission: "8-speed DCT",
    drive: "RWD",
    environment: "architecture",
    silhouette: "coupe",
    hue: 350,
    tagline: "La Nuova Dolce Vita — Ferrari's grand tourer for the modern era.",
    description:
      "Where most Ferraris shout, the Roma speaks softly. A long, uninterrupted bonnet and a fastback roofline reference the brand's 1960s front-engined coupes, wrapped around a twin-turbo V8 that still delivers everything you'd expect.",
    interiorNote:
      "A dual-cockpit layout gives driver and passenger their own dedicated displays, finished in an interior that feels closer to a boutique hotel than a race shop.",
    feelings: ["luxury", "attention"],
    related: ["aston-martin-db12", "bentley-continental-gt-speed", "mercedes-amg-gt-63-s"],
  },
  {
    slug: "aston-martin-db12",
    brand: "Aston Martin",
    model: "DB12",
    category: "sports",
    year: 2024,
    priceFrom: 990000,
    horsepower: 671,
    torqueNm: 800,
    zeroToHundred: 3.6,
    topSpeed: 325,
    weightKg: 1685,
    fuelType: "Petrol",
    transmission: "8-speed AT",
    drive: "RWD",
    environment: "mountain",
    silhouette: "coupe",
    hue: 150,
    tagline: "Aston Martin calls it the first 'super tourer.' It means every word.",
    description:
      "A twin-turbo V8 tuned in-house, a chassis stiffened by 7%, and enough new technology to close the gap to the segment's fastest cars — without losing the long-legged manners a DB has always been known for.",
    interiorNote:
      "British leather, real metal switchgear, and a new interface designed to keep the cabin feeling handcrafted even as the tech underneath gets sharper.",
    feelings: ["luxury", "speed"],
    related: ["ferrari-roma", "bentley-continental-gt-speed", "jaguar-f-type-r"],
  },
  {
    slug: "toyota-gr-supra",
    brand: "Toyota",
    model: "GR Supra",
    category: "sports",
    year: 2024,
    priceFrom: 235000,
    horsepower: 382,
    torqueNm: 500,
    zeroToHundred: 3.9,
    topSpeed: 250,
    weightKg: 1550,
    fuelType: "Petrol",
    transmission: "8-speed AT",
    drive: "RWD",
    environment: "track",
    silhouette: "coupe",
    hue: 340,
    tagline: "The name came back. So did the point of it.",
    description:
      "A low center of gravity, a near-perfect 50:50 weight balance, and a straight-six that loves to be revved. Proof that a sports car doesn't need a supercar price tag to be genuinely thrilling on a back road.",
    interiorNote:
      "A snug two-seat cockpit built around the driver, with a wide double-bubble roof that leaves just enough headroom for a helmet on track days.",
    feelings: ["speed", "adventure"],
    related: ["nissan-gt-r-nismo", "bmw-m4-competition", "chevrolet-corvette-z06"],
  },
  {
    slug: "bmw-m4-competition",
    brand: "BMW",
    model: "M4 Competition",
    category: "sports",
    year: 2024,
    priceFrom: 385000,
    horsepower: 503,
    torqueNm: 650,
    zeroToHundred: 3.5,
    topSpeed: 290,
    weightKg: 1725,
    fuelType: "Petrol",
    transmission: "8-speed AT",
    drive: "RWD",
    environment: "night-city",
    silhouette: "coupe",
    hue: 205,
    tagline: "The daily driver that turns into a track weapon on demand.",
    description:
      "A twin-turbo straight-six with the sharpness of a race engine and the reliability of a company car. Adjustable everything — drift mode included — means it can be exactly as wild as the driver wants, whenever they want it.",
    interiorNote:
      "Carbon bucket seats, illuminated M badging, and a curved digital display that keeps every performance metric one glance away.",
    feelings: ["speed", "technology"],
    related: ["mercedes-amg-gt-63-s", "toyota-gr-supra", "nissan-gt-r-nismo"],
  },
  {
    slug: "mercedes-s580",
    brand: "Mercedes-Benz",
    model: "S 580",
    category: "luxury",
    year: 2024,
    priceFrom: 750000,
    horsepower: 429,
    torqueNm: 520,
    zeroToHundred: 4.9,
    topSpeed: 250,
    weightKg: 2185,
    fuelType: "Petrol",
    transmission: "9-speed AT",
    drive: "AWD",
    environment: "architecture",
    silhouette: "sedan",
    hue: 45,
    tagline: "The car every other luxury sedan is still measured against.",
    description:
      "Rear-axle steering shrinks it in car parks and stretches it on the highway, while active suspension reads the road ahead and adjusts before you feel a thing. It doesn't chase headlines — it simply sets the benchmark, again.",
    interiorNote:
      "Twin curved OLED displays, massaging rear seats, and cabin air filtration precise enough to be measured in microns. This is where the S-Class has always won.",
    feelings: ["luxury", "technology"],
    related: ["bentley-continental-gt-speed", "rolls-royce-spectre", "bmw-i7-m70"],
  },
  {
    slug: "bentley-continental-gt-speed",
    brand: "Bentley",
    model: "Continental GT Speed",
    category: "luxury",
    year: 2024,
    priceFrom: 1050000,
    horsepower: 650,
    torqueNm: 900,
    zeroToHundred: 3.2,
    topSpeed: 335,
    weightKg: 2280,
    fuelType: "Hybrid",
    transmission: "8-speed DCT",
    drive: "AWD",
    environment: "mountain",
    silhouette: "coupe",
    hue: 40,
    tagline: "2.3 tonnes of handcrafted British grand touring, doing 335 km/h.",
    description:
      "A plug-in hybrid W12 replacement powertrain hidden inside a body that still takes over 100 hours to hand-finish. Whichever road you point it down, it arrives having made the journey feel shorter than it was.",
    interiorNote:
      "Rotating dashboard display, diamond-quilted leather, and enough wood veneer, hand-cut from a single tree, to line every panel with a matching grain.",
    feelings: ["luxury", "speed"],
    related: ["mercedes-s580", "aston-martin-db12", "rolls-royce-spectre"],
  },
  {
    slug: "rolls-royce-spectre",
    brand: "Rolls-Royce",
    model: "Spectre",
    category: "luxury",
    year: 2024,
    priceFrom: 1450000,
    horsepower: 577,
    torqueNm: 900,
    zeroToHundred: 4.5,
    topSpeed: 250,
    weightKg: 2975,
    fuelType: "Electric",
    transmission: "Single-speed",
    drive: "AWD",
    environment: "architecture",
    silhouette: "coupe",
    hue: 275,
    tagline: "Rolls-Royce's first electric car — and, they insist, the truest one yet.",
    description:
      "Silence was always the goal at Rolls-Royce; an electric powertrain simply gets there faster. Nearly 700 kilograms of battery are hidden low in the chassis, giving the two-tonne-plus coupé a planted, unshakeable calm.",
    interiorNote:
      "A starlight headliner with over 5,000 fibre-optic points, hand-stitched to resemble a shooting star crossing the cabin roof — a signature carried over from the marque's combustion cars.",
    feelings: ["luxury", "future"],
    related: ["bentley-continental-gt-speed", "bmw-i7-m70", "bugatti-chiron-super-sport"],
  },
  {
    slug: "porsche-taycan-turbo-s",
    brand: "Porsche",
    model: "Taycan Turbo S",
    category: "electric",
    year: 2024,
    priceFrom: 780000,
    horsepower: 750,
    torqueNm: 1050,
    zeroToHundred: 2.8,
    topSpeed: 260,
    weightKg: 2295,
    fuelType: "Electric",
    transmission: "2-speed",
    drive: "AWD",
    environment: "night-city",
    silhouette: "sedan",
    hue: 84,
    tagline: "Proof an electric car can still feel like a Porsche.",
    description:
      "A two-speed rear transmission — rare in an EV — keeps launch acceleration brutal and top-end pull strong. Repeated full-power launches barely dent its performance, something few electric performance cars can claim.",
    interiorNote:
      "Four individual displays, including one for the front passenger, wrapped around a driving position that still feels unmistakably 911-adjacent.",
    feelings: ["future", "technology", "speed"],
    related: ["audi-rs-e-tron-gt", "tesla-model-s-plaid", "bmw-i7-m70"],
  },
  {
    slug: "bmw-i7-m70",
    brand: "BMW",
    model: "i7 M70",
    category: "electric",
    year: 2024,
    priceFrom: 895000,
    horsepower: 660,
    torqueNm: 1015,
    zeroToHundred: 3.7,
    topSpeed: 250,
    weightKg: 2745,
    fuelType: "Electric",
    transmission: "Single-speed",
    drive: "AWD",
    environment: "architecture",
    silhouette: "sedan",
    hue: 190,
    tagline: "BMW's flagship, reimagined without a drop of fuel.",
    description:
      "The most powerful M car BMW has ever built happens to be electric. A 31-inch theatre screen folds down from the rear roofline for back-seat passengers who'd rather not watch the road at all.",
    interiorNote:
      "Crystal-look controls, illuminated fabric on the dash, and rear reclining seats with their own ottomans — built for being driven as much as driving.",
    feelings: ["future", "luxury"],
    related: ["mercedes-s580", "rolls-royce-spectre", "porsche-taycan-turbo-s"],
  },
  {
    slug: "audi-rs-e-tron-gt",
    brand: "Audi",
    model: "RS e-tron GT",
    category: "electric",
    year: 2024,
    priceFrom: 690000,
    horsepower: 646,
    torqueNm: 830,
    zeroToHundred: 3.3,
    topSpeed: 250,
    weightKg: 2347,
    fuelType: "Electric",
    transmission: "2-speed",
    drive: "AWD",
    environment: "night-city",
    silhouette: "sedan",
    hue: 15,
    tagline: "The four-door that made Audi's electric future look this good.",
    description:
      "Shares its underpinnings with the Taycan but wraps them in a lower, more aggressive shooting-brake silhouette. 800-volt architecture means a fast-charge stop rarely lasts longer than a coffee.",
    interiorNote:
      "A driver-angled cockpit with a flat-bottom wheel and recycled-material trim throughout — proof that sustainable doesn't have to mean plain.",
    feelings: ["future", "speed"],
    related: ["porsche-taycan-turbo-s", "tesla-model-s-plaid", "bmw-i7-m70"],
  },
  {
    slug: "tesla-model-s-plaid",
    brand: "Tesla",
    model: "Model S Plaid",
    category: "electric",
    year: 2024,
    priceFrom: 520000,
    horsepower: 1020,
    torqueNm: 1420,
    zeroToHundred: 2.1,
    topSpeed: 322,
    weightKg: 2162,
    fuelType: "Electric",
    transmission: "Single-speed",
    drive: "AWD",
    environment: "architecture",
    silhouette: "sedan",
    hue: 0,
    tagline: "Three motors. One number that still doesn't sound real: 2.1 seconds.",
    description:
      "Tri-motor, carbon-sleeve rotors spinning past 20,000 rpm, and a steering yoke that makes the whole cabin feel like a cockpit. Nothing on sale accelerates harder for the price — very little accelerates harder at any price.",
    interiorNote:
      "A minimalist cabin built around one central screen, with a rear display for passengers and near-silent cabin insulation at highway speed.",
    feelings: ["future", "technology", "speed"],
    related: ["porsche-taycan-turbo-s", "audi-rs-e-tron-gt", "bugatti-chiron-super-sport"],
  },
  {
    slug: "lamborghini-urus-s",
    brand: "Lamborghini",
    model: "Urus S",
    category: "suv",
    year: 2024,
    priceFrom: 960000,
    horsepower: 666,
    torqueNm: 850,
    zeroToHundred: 3.5,
    topSpeed: 305,
    weightKg: 2200,
    fuelType: "Petrol",
    transmission: "8-speed AT",
    drive: "AWD",
    environment: "desert",
    silhouette: "suv",
    hue: 52,
    tagline: "The SUV that made Lamborghini profitable enough to keep building supercars.",
    description:
      "A twin-turbo V8 shared with the brand's sports cars, dropped into a body tall enough to clear real terrain and still hit a claimed 305 km/h. Six drive modes, including one specifically tuned for sand.",
    interiorNote:
      "Four individual sport seats, a honeycomb-stitched dash, and the same hexagonal design language borrowed straight from the Huracán.",
    feelings: ["speed", "attention"],
    related: ["range-rover-sport-sv", "bentley-continental-gt-speed", "mercedes-amg-gt-63-s"],
  },
  {
    slug: "range-rover-sport-sv",
    brand: "Range Rover",
    model: "Sport SV",
    category: "suv",
    year: 2024,
    priceFrom: 890000,
    horsepower: 626,
    torqueNm: 750,
    zeroToHundred: 3.6,
    topSpeed: 290,
    weightKg: 2485,
    fuelType: "Petrol",
    transmission: "8-speed AT",
    drive: "AWD",
    environment: "desert",
    silhouette: "suv",
    hue: 20,
    tagline: "The most focused Range Rover ever built — still happiest off-road.",
    description:
      "6D Dynamics active suspension keeps body roll almost nonexistent through corners, then softens completely the moment the tarmac runs out. Few vehicles are this composed on both a hillclimb and a dune.",
    interiorNote:
      "Semi-aniline leather, a 13.1-inch curved display, and a cabin quiet enough at speed that conversation never has to compete with the engine.",
    feelings: ["luxury", "adventure"],
    related: ["lamborghini-urus-s", "volvo-ex90", "bentley-continental-gt-speed"],
  },
  {
    slug: "volvo-ex90",
    brand: "Volvo",
    model: "EX90",
    category: "suv",
    year: 2024,
    priceFrom: 340000,
    horsepower: 517,
    torqueNm: 910,
    zeroToHundred: 4.7,
    topSpeed: 180,
    weightKg: 2860,
    fuelType: "Electric",
    transmission: "Single-speed",
    drive: "AWD",
    environment: "architecture",
    silhouette: "suv",
    hue: 210,
    tagline: "Volvo's flagship electric SUV, built around one idea: everyone comes home.",
    description:
      "A roof-mounted LiDAR sensor scans the road nearly 250 metres ahead, feeding a safety system Volvo has spent a decade building. Seven seats, a near-silent cabin, and enough range for a full day without a second thought.",
    interiorNote:
      "Scandinavian minimalism throughout, with wool-blend upholstery, ambient lighting, and a bioacoustic sensor that can detect a heartbeat left behind in the cabin.",
    feelings: ["future", "technology"],
    related: ["range-rover-sport-sv", "audi-rs-e-tron-gt", "bmw-i7-m70"],
  },
  {
    slug: "mercedes-amg-gt-63-s",
    brand: "Mercedes-Benz",
    model: "AMG GT 63 S",
    category: "performance",
    year: 2024,
    priceFrom: 780000,
    horsepower: 630,
    torqueNm: 900,
    zeroToHundred: 3.2,
    topSpeed: 315,
    weightKg: 2045,
    fuelType: "Petrol",
    transmission: "9-speed AT",
    drive: "AWD",
    environment: "mountain",
    silhouette: "sedan",
    hue: 195,
    tagline: "A four-door that still remembers it wears an AMG badge.",
    description:
      "Rear-wheel steering and a fully variable all-wheel-drive system let it swing from stable family hauler to tail-happy sports car with one press of the drift-mode button. The hand-built V8 up front never lets you forget it's there.",
    interiorNote:
      "AMG's signature turbine air vents, a widescreen cockpit display, and four individually contoured seats built for long, fast drives.",
    feelings: ["speed", "luxury"],
    related: ["bmw-m4-competition", "nissan-gt-r-nismo", "ferrari-roma"],
  },
  {
    slug: "nissan-gt-r-nismo",
    brand: "Nissan",
    model: "GT-R Nismo",
    category: "performance",
    year: 2023,
    priceFrom: 410000,
    horsepower: 600,
    torqueNm: 652,
    zeroToHundred: 2.8,
    topSpeed: 315,
    weightKg: 1720,
    fuelType: "Petrol",
    transmission: "6-speed DCT",
    drive: "AWD",
    environment: "night-city",
    silhouette: "coupe",
    hue: 340,
    tagline: "Godzilla, still undefeated after almost two decades.",
    description:
      "A hand-built twin-turbo V6, carbon aero borrowed from Nissan's GT3 racing program, and a launch-control system that turns 2.8 seconds to 100 km/h into a repeatable party trick rather than a one-time stunt.",
    interiorNote:
      "Recaro carbon bucket seats and a Nismo-specific gauge cluster, built to survive a track day and still be usable the next morning commute.",
    feelings: ["speed", "technology"],
    related: ["toyota-gr-supra", "bmw-m4-competition", "audi-r8-v10"],
  },
  {
    slug: "chevrolet-corvette-z06",
    brand: "Chevrolet",
    model: "Corvette Z06",
    category: "classics",
    year: 2024,
    priceFrom: 460000,
    horsepower: 670,
    torqueNm: 623,
    zeroToHundred: 2.6,
    topSpeed: 314,
    weightKg: 1560,
    fuelType: "Petrol",
    transmission: "8-speed DCT",
    drive: "RWD",
    environment: "studio",
    silhouette: "classic",
    hue: 5,
    tagline: "America's sports car, mid-engined for the first time in seven decades.",
    description:
      "A flat-plane-crank V8 that revs to 8,600 rpm — a sound and a redline no previous Corvette ever had. Moving the engine behind the driver finally puts it on paper against the exotics it's always chased.",
    interiorNote:
      "A driver-wrapped cockpit with a squared-off wheel and passenger-side switch wall, keeping every control angled toward the person actually driving.",
    feelings: ["speed", "attention"],
    related: ["toyota-gr-supra", "jaguar-f-type-r", "nissan-gt-r-nismo"],
  },
  {
    slug: "jaguar-f-type-r",
    brand: "Jaguar",
    model: "F-Type R",
    category: "classics",
    year: 2023,
    priceFrom: 430000,
    horsepower: 575,
    torqueNm: 700,
    zeroToHundred: 3.5,
    topSpeed: 300,
    weightKg: 1730,
    fuelType: "Petrol",
    transmission: "8-speed AT",
    drive: "AWD",
    environment: "mountain",
    silhouette: "classic",
    hue: 150,
    tagline: "The last of Jaguar's supercharged V8 sports cars.",
    description:
      "Long bonnet, short rear deck, a cabin set well back over the rear axle — proportions lifted straight from the E-Type playbook. A supercharged V8 gives it a soundtrack no turbocharged rival can quite match.",
    interiorNote:
      "Analogue-inspired toggle switches and a leather-wrapped cabin that leans on heritage cues rather than screens for its sense of occasion.",
    feelings: ["attention", "adventure"],
    related: ["chevrolet-corvette-z06", "aston-martin-db12", "ferrari-roma"],
  },
];

export const brands: Brand[] = [
  { name: "Porsche", country: "Germany", founded: 1931 },
  { name: "Ferrari", country: "Italy", founded: 1939 },
  { name: "Lamborghini", country: "Italy", founded: 1963 },
  { name: "McLaren", country: "United Kingdom", founded: 1963 },
  { name: "Audi", country: "Germany", founded: 1909 },
  { name: "Bugatti", country: "France", founded: 1909 },
  { name: "Aston Martin", country: "United Kingdom", founded: 1913 },
  { name: "Toyota", country: "Japan", founded: 1937 },
  { name: "BMW", country: "Germany", founded: 1916 },
  { name: "Mercedes-Benz", country: "Germany", founded: 1926 },
  { name: "Bentley", country: "United Kingdom", founded: 1919 },
  { name: "Rolls-Royce", country: "United Kingdom", founded: 1904 },
  { name: "Tesla", country: "United States", founded: 2003 },
  { name: "Range Rover", country: "United Kingdom", founded: 1970 },
  { name: "Volvo", country: "Sweden", founded: 1927 },
  { name: "Nissan", country: "Japan", founded: 1933 },
  { name: "Chevrolet", country: "United States", founded: 1911 },
  { name: "Jaguar", country: "United Kingdom", founded: 1935 },
];

export const stories: Story[] = [
  {
    slug: "why-legends",
    kicker: "The Long Read",
    title: "Why Some Cars Become Legends.",
    excerpt:
      "It's rarely the fastest number that makes a car immortal. It's the ones that got the feeling right — the sound, the shape, the moment the engine catches. A look at what actually separates a good car from one people still talk about decades later.",
    hue: 84,
  },
  {
    slug: "electric-performance",
    kicker: "The Future",
    title: "The Future of Electric Performance.",
    excerpt:
      "Instant torque changed the definition of fast before anyone agreed on what an electric performance car was supposed to sound like. From the Taycan to the Plaid, the case for silence as its own kind of thrill.",
    hue: 190,
  },
  {
    slug: "911-never-dies",
    kicker: "Heritage",
    title: "Why the Porsche 911 Never Dies.",
    excerpt:
      "Same silhouette since 1963. Same rear-engined layout everyone said wouldn't work. Six decades and eight generations later, the 911 is still the car every other sports car gets measured against — and nobody can quite explain why better than it explains itself.",
    hue: 84,
  },
  {
    slug: "most-beautiful",
    kicker: "Design",
    title: "The Most Beautiful Cars Ever Designed.",
    excerpt:
      "Beauty in a car isn't decoration — it's a byproduct of decisions made for entirely different reasons: airflow, weight, a designer refusing to round off one more edge. A study of proportion, stance, and the shapes that still stop people on the street.",
    hue: 40,
  },
];
