import type { Brand, Model, Part, PartCategory } from "./types";

export const brands: Brand[] = [
  { id: "bmw", name: "بي إم دبليو", nameEn: "BMW", hue: 205 },
  { id: "mercedes", name: "مرسيدس-بنز", nameEn: "Mercedes-Benz", hue: 195 },
  { id: "porsche", name: "بورش", nameEn: "Porsche", hue: 20 },
  { id: "audi", name: "أودي", nameEn: "Audi", hue: 0 },
  { id: "tesla", name: "تسلا", nameEn: "Tesla", hue: 350 },
  { id: "toyota", name: "تويوتا", nameEn: "Toyota", hue: 0 },
  { id: "nissan", name: "نيسان", nameEn: "Nissan", hue: 210 },
  { id: "ford", name: "فورد", nameEn: "Ford", hue: 210 },
  { id: "chevrolet", name: "شيفروليه", nameEn: "Chevrolet", hue: 40 },
  { id: "lamborghini", name: "لامبورغيني", nameEn: "Lamborghini", hue: 52 },
  { id: "ferrari", name: "فيراري", nameEn: "Ferrari", hue: 4 },
  { id: "mclaren", name: "مكلارين", nameEn: "McLaren", hue: 24 },
];

export const models: Model[] = [
  { id: "bmw-3-series", brandId: "bmw", name: "الفئة الثالثة", yearFrom: 2015, yearTo: 2024 },
  { id: "bmw-x5", brandId: "bmw", name: "X5", yearFrom: 2015, yearTo: 2023 },
  { id: "bmw-m4", brandId: "bmw", name: "M4", yearFrom: 2021, yearTo: 2024 },

  { id: "mb-c-class", brandId: "mercedes", name: "الفئة C", yearFrom: 2015, yearTo: 2023 },
  { id: "mb-e-class", brandId: "mercedes", name: "الفئة E", yearFrom: 2017, yearTo: 2024 },
  { id: "mb-gle", brandId: "mercedes", name: "GLE", yearFrom: 2016, yearTo: 2023 },

  { id: "porsche-911", brandId: "porsche", name: "911", yearFrom: 2015, yearTo: 2024 },
  { id: "porsche-cayenne", brandId: "porsche", name: "Cayenne", yearFrom: 2015, yearTo: 2023 },
  { id: "porsche-macan", brandId: "porsche", name: "Macan", yearFrom: 2015, yearTo: 2023 },

  { id: "audi-a4", brandId: "audi", name: "A4", yearFrom: 2016, yearTo: 2023 },
  { id: "audi-q5", brandId: "audi", name: "Q5", yearFrom: 2018, yearTo: 2024 },
  { id: "audi-a6", brandId: "audi", name: "A6", yearFrom: 2015, yearTo: 2023 },

  { id: "tesla-model-3", brandId: "tesla", name: "Model 3", yearFrom: 2018, yearTo: 2024 },
  { id: "tesla-model-y", brandId: "tesla", name: "Model Y", yearFrom: 2020, yearTo: 2024 },

  { id: "toyota-camry", brandId: "toyota", name: "كامري", yearFrom: 2018, yearTo: 2024 },
  { id: "toyota-corolla", brandId: "toyota", name: "كورولا", yearFrom: 2017, yearTo: 2024 },
  { id: "toyota-land-cruiser", brandId: "toyota", name: "لاند كروزر", yearFrom: 2012, yearTo: 2024 },
  { id: "toyota-hilux", brandId: "toyota", name: "هايلكس", yearFrom: 2016, yearTo: 2024 },

  { id: "nissan-altima", brandId: "nissan", name: "التيما", yearFrom: 2019, yearTo: 2024 },
  { id: "nissan-patrol", brandId: "nissan", name: "باترول", yearFrom: 2017, yearTo: 2024 },
  { id: "nissan-sunny", brandId: "nissan", name: "صني", yearFrom: 2016, yearTo: 2024 },

  { id: "ford-f150", brandId: "ford", name: "F-150", yearFrom: 2015, yearTo: 2024 },
  { id: "ford-explorer", brandId: "ford", name: "إكسبلورر", yearFrom: 2016, yearTo: 2024 },

  { id: "chevrolet-tahoe", brandId: "chevrolet", name: "تاهو", yearFrom: 2015, yearTo: 2023 },
  { id: "chevrolet-camaro", brandId: "chevrolet", name: "كامارو", yearFrom: 2016, yearTo: 2024 },

  { id: "lambo-huracan", brandId: "lamborghini", name: "هوراكان", yearFrom: 2015, yearTo: 2024 },
  { id: "lambo-urus", brandId: "lamborghini", name: "أوروس", yearFrom: 2018, yearTo: 2024 },

  { id: "ferrari-488", brandId: "ferrari", name: "488", yearFrom: 2015, yearTo: 2020 },
  { id: "ferrari-roma", brandId: "ferrari", name: "روما", yearFrom: 2020, yearTo: 2024 },

  { id: "mclaren-720s", brandId: "mclaren", name: "720S", yearFrom: 2017, yearTo: 2024 },
];

export const categories: PartCategory[] = [
  { id: "engine", name: "المحرك", line: "قلب السيارة، وأكثر قطعة تتحدد بها بقية القطع.", icon: "engine" },
  { id: "exhaust", name: "العادم", line: "من الكاتم إلى الكاتالايزر، بصوت وأداء أفضل.", icon: "exhaust" },
  { id: "brakes", name: "الفرامل", line: "أهم قطعة أمان في سيارتك، بلا استثناء.", icon: "brakes" },
  { id: "wheels", name: "الإطارات والعجلات", line: "الملامسة الوحيدة بينك وبين الطريق.", icon: "wheels" },
  { id: "suspension", name: "التعليق", line: "ثبات القيادة وراحتها في كل حفرة ومطب.", icon: "suspension" },
  { id: "performance", name: "قطع الأداء", line: "لمن يبي يطلّع أقصى ما عند سيارته.", icon: "performance" },
  { id: "exterior", name: "الخارجية", line: "المظهر الخارجي — من المصدات إلى المرايا.", icon: "exterior" },
  { id: "interior", name: "الداخلية", line: "راحتك وتفاصيل المقصورة من الداخل.", icon: "interior" },
  { id: "lighting", name: "الإضاءة", line: "رؤية أوضح، وحضور أقوى بالليل.", icon: "lighting" },
];

export const parts: Part[] = [
  // ---------- المحرك ----------
  {
    id: "air-filter-performance",
    categoryId: "engine",
    name: "فلتر هواء أداء عالي",
    brandLabel: "K&N",
    price: 145,
    stockCount: 22,
    hue: 84,
    compatibleModelIds: ["toyota-camry", "toyota-corolla", "nissan-altima"],
    yearFrom: 2017,
    yearTo: 2024,
    specs: [
      { label: "النوع", value: "قابل للغسل وإعادة الاستخدام" },
      { label: "زيادة تدفق الهواء", value: "حتى ٪50" },
      { label: "الضمان", value: "سنة واحدة" },
    ],
    description: "فلتر هواء رياضي قابل للغسل، يحسّن تدفق الهواء للمحرك مقارنة بالفلتر الورقي الأصلي دون التأثير على الحماية من الأتربة.",
    installNote: "تركيب مباشر مكان الفلتر الأصلي، بدون تعديلات — يستغرق أقل من 10 دقائق.",
    related: ["spark-plugs-iridium", "cold-air-intake"],
    popular: true,
  },
  {
    id: "spark-plugs-iridium",
    categoryId: "engine",
    name: "طقم بواجي إيريديوم",
    brandLabel: "NGK",
    price: 320,
    stockCount: 14,
    hue: 205,
    compatibleModelIds: ["bmw-3-series", "mb-c-class", "audi-a4"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "العدد", value: "طقم 4 بواجي" },
      { label: "العمر الافتراضي", value: "حتى 100,000 كم" },
      { label: "المادة", value: "إيريديوم" },
    ],
    description: "بواجي إيريديوم بعمر تشغيلي أطول من البواجي التقليدية، وإشعال أكثر ثباتاً يحسّن استهلاك الوقود ونعومة المحرك.",
    installNote: "يفضّل التركيب عند فني مختص لضبط عزم الربط الصحيح.",
    related: ["air-filter-performance", "engine-mount"],
  },
  {
    id: "water-pump",
    categoryId: "engine",
    name: "مضخة مياه أصلية",
    brandLabel: "Toyota Genuine",
    price: 480,
    stockCount: 9,
    hue: 24,
    compatibleModelIds: ["toyota-land-cruiser", "toyota-hilux", "nissan-patrol"],
    yearFrom: 2012,
    yearTo: 2024,
    specs: [
      { label: "النوع", value: "أصلي (OEM)" },
      { label: "يشمل", value: "حشوة جديدة" },
      { label: "الضمان", value: "سنتان" },
    ],
    description: "مضخة مياه أصلية تضمن دوران سليم لسائل التبريد ومنع ارتفاع حرارة المحرك، خصوصاً في القيادة الطويلة أو الأجواء الحارة.",
    installNote: "يتطلب تفريغ سائل التبريد قبل التركيب — ضمن خدمات الورشة المتوفرة معنا.",
    related: ["engine-mount", "air-filter-performance"],
  },
  {
    id: "engine-mount",
    categoryId: "engine",
    name: "كراسي محرك (مجموعة)",
    brandLabel: "Febi",
    price: 380,
    stockCount: 12,
    hue: 40,
    compatibleModelIds: ["ford-f150", "chevrolet-tahoe", "nissan-altima"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "العدد", value: "طقم كامل" },
      { label: "المادة", value: "مطاط مقوى + معدن" },
    ],
    description: "كراسي محرك جديدة تقلل الاهتزاز والضوضاء الناتجة عن تآكل الكراسي الأصلية مع عمر السيارة.",
    installNote: "يُنصح باستبدالها كطقم كامل وليس قطعة واحدة لتوازن أفضل.",
    related: ["water-pump", "spark-plugs-iridium"],
  },

  // ---------- العادم ----------
  {
    id: "sport-muffler",
    categoryId: "exhaust",
    name: "كاتم صوت رياضي ستانلس",
    brandLabel: "Akrapovič",
    price: 3200,
    stockCount: 4,
    hue: 84,
    compatibleModelIds: ["bmw-m4", "ferrari-488", "lambo-huracan"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "ستانلس ستيل" },
      { label: "الصوت", value: "رياضي عميق، قابل للتعديل" },
      { label: "الوزن", value: "أخف من الأصلي بـ ٪30" },
    ],
    description: "كاتم صوت رياضي مصنوع بالكامل من الستانلس، يمنح صوتاً أعمق وتدفق عادم أفضل مع تقليل الوزن الكلي للسيارة.",
    installNote: "تركيب احترافي موصى به — يشمل شفة تثبيت مخصصة لكل موديل.",
    related: ["catalytic-converter", "flex-pipe"],
    popular: true,
  },
  {
    id: "chrome-exhaust-tip",
    categoryId: "exhaust",
    name: "طرف عادم مزدوج كروم",
    brandLabel: "Borla",
    price: 380,
    stockCount: 11,
    hue: 195,
    compatibleModelIds: ["mb-c-class", "chevrolet-camaro", "toyota-camry"],
    yearFrom: 2016,
    yearTo: 2024,
    specs: [
      { label: "التشطيب", value: "كروم لامع" },
      { label: "القطر", value: "مزدوج 3.5 بوصة" },
    ],
    description: "طرف عادم كروم مزدوج يضيف لمسة رياضية للمظهر الخلفي دون التأثير على أداء المحرك.",
    installNote: "تركيب بالقص واللحام أو بمشابك حسب نوع نظام العادم الأصلي.",
    related: ["sport-muffler", "flex-pipe"],
  },
  {
    id: "flex-pipe",
    categoryId: "exhaust",
    name: "مرن عادم (فلكس بايب)",
    brandLabel: "Walker",
    price: 165,
    stockCount: 19,
    hue: 350,
    compatibleModelIds: ["toyota-corolla", "nissan-sunny"],
    yearFrom: 2016,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "ستانلس مضفّر" },
      { label: "الوظيفة", value: "امتصاص اهتزاز المحرك" },
    ],
    description: "قطعة مرنة تمتص حركة واهتزاز المحرك وتمنع تشقق أنبوب العادم مع الوقت.",
    installNote: "يُستبدل غالباً مع ظهور صوت طرقعة معدنية عند التسارع.",
    related: ["chrome-exhaust-tip", "catalytic-converter"],
  },
  {
    id: "catalytic-converter",
    categoryId: "exhaust",
    name: "كاتالايزر (محول حفّاز)",
    brandLabel: "Bosal",
    price: 1450,
    stockCount: 6,
    hue: 20,
    compatibleModelIds: ["bmw-3-series", "audi-a4"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "المعيار", value: "متوافق مع معايير الانبعاثات" },
      { label: "الضمان", value: "سنتان" },
    ],
    description: "يحوّل الغازات الضارة في العادم إلى مركبات أقل ضرراً، وهو أحد أكثر أسباب فشل فحص الانبعاثات عند تلفه.",
    installNote: "استبدال بواسطة فني مختص، يشمل فحص حساسات الأكسجين المرتبطة به.",
    related: ["flex-pipe", "sport-muffler"],
  },

  // ---------- الفرامل ----------
  {
    id: "ceramic-brake-pads-front",
    categoryId: "brakes",
    name: "طقم تيل فرامل أمامي سيراميك",
    brandLabel: "Brembo",
    price: 420,
    stockCount: 13,
    hue: 205,
    compatibleModelIds: ["porsche-911", "bmw-m4", "audi-a6"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "سيراميك" },
      { label: "الغبار", value: "أقل بكثير من التيل العادي" },
      { label: "الصوت", value: "هادئ" },
    ],
    description: "تيل فرامل سيراميك يوفر كبح ثابت وهادئ مع غبار أقل على الجنطات، مناسب للاستخدام اليومي والقيادة الرياضية معاً.",
    installNote: "يُنصح بتغيير الأقراص معه إذا تجاوزت 60% من عمرها الافتراضي.",
    related: ["drilled-brake-discs", "brake-hose"],
    popular: true,
  },
  {
    id: "drilled-brake-discs",
    categoryId: "brakes",
    name: "أقراص فرامل مثقبة",
    brandLabel: "Zimmermann",
    price: 1850,
    stockCount: 5,
    hue: 24,
    compatibleModelIds: ["mclaren-720s", "lambo-huracan", "ferrari-roma"],
    yearFrom: 2017,
    yearTo: 2024,
    specs: [
      { label: "النوع", value: "مثقبة ومهواة" },
      { label: "المقاومة الحرارية", value: "عالية جداً" },
    ],
    description: "أقراص مثقبة ومهواة تبدد الحرارة بسرعة أكبر وتقاوم التبخّر الحراري (Brake Fade) عند القيادة الرياضية أو المضمار.",
    installNote: "يُنصح باستخدامها مع تيل فرامل سيراميك أو رياضي للحصول على أفضل أداء.",
    related: ["ceramic-brake-pads-front", "brake-hose"],
  },
  {
    id: "economy-brake-pads-rear",
    categoryId: "brakes",
    name: "تيل فرامل خلفي اقتصادي",
    brandLabel: "Bosch",
    price: 175,
    stockCount: 28,
    hue: 40,
    compatibleModelIds: ["toyota-camry", "toyota-corolla", "nissan-altima"],
    yearFrom: 2017,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "شبه معدني" },
      { label: "العمر المتوقع", value: "حتى 40,000 كم" },
    ],
    description: "خيار اقتصادي وموثوق لتيل الفرامل الخلفي، يغطي الاستخدام اليومي العادي بجودة Bosch المعروفة.",
    installNote: "تركيب قياسي — يشمل فحص مجاني لحالة الأقراص عند الطلب.",
    related: ["ceramic-brake-pads-front", "brake-hose"],
  },
  {
    id: "brake-hose",
    categoryId: "brakes",
    name: "خرطوم فرامل ستانلس",
    brandLabel: "Goodridge",
    price: 240,
    stockCount: 16,
    hue: 195,
    compatibleModelIds: ["bmw-3-series", "mb-c-class"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "مضفّر ستانلس" },
      { label: "الفائدة", value: "دواسة فرامل أصلب وأدق" },
    ],
    description: "خراطيم فرامل مضفّرة تقلل من مرونة الخرطوم المطاطي الأصلي، فتشعر بدواسة فرامل أكثر دقة واستجابة.",
    installNote: "يتطلب تنفيس نظام الفرامل بالكامل بعد التركيب.",
    related: ["ceramic-brake-pads-front", "drilled-brake-discs"],
  },

  // ---------- الإطارات والعجلات ----------
  {
    id: "sport-tires-19",
    categoryId: "wheels",
    name: "طقم إطارات رياضية 19 بوصة",
    brandLabel: "Michelin Pilot Sport",
    price: 2600,
    stockCount: 8,
    hue: 205,
    compatibleModelIds: ["bmw-m4", "mb-e-class", "audi-a6", "mb-gle"],
    yearFrom: 2017,
    yearTo: 2024,
    specs: [
      { label: "المقاس", value: "19 بوصة" },
      { label: "العدد", value: "طقم 4 إطارات" },
      { label: "التصنيف", value: "أداء عالي" },
    ],
    description: "إطارات رياضية بتماسك عالي في المنعطفات وكبح أقصر، مصممة للقيادة الحماسية والاستخدام اليومي معاً.",
    installNote: "يشمل توازن الجنط وضبط الزوايا (أربع عجلات).",
    related: ["black-alloy-wheels", "tpms-sensor"],
    popular: true,
  },
  {
    id: "black-alloy-wheels",
    categoryId: "wheels",
    name: "جنط ألمنيوم أسود مطفي",
    brandLabel: "OZ Racing",
    price: 1350,
    stockCount: 10,
    hue: 40,
    compatibleModelIds: ["toyota-land-cruiser", "nissan-patrol", "ford-f150", "bmw-x5"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "ألمنيوم مصبوب" },
      { label: "اللون", value: "أسود مطفي" },
    ],
    description: "جنط ألمنيوم بتصميم قوي يناسب الدفع الرباعي والسيارات الكبيرة، مع طلاء مقاوم للخدوش والصدأ.",
    installNote: "يشمل صواميل تثبيت مطابقة ومفتاح أمان.",
    related: ["sport-tires-19", "tpms-sensor"],
  },
  {
    id: "winter-tires",
    categoryId: "wheels",
    name: "إطار موسمي (شتوي)",
    brandLabel: "Continental",
    price: 780,
    stockCount: 12,
    hue: 0,
    compatibleModelIds: ["tesla-model-3", "tesla-model-y"],
    yearFrom: 2018,
    yearTo: 2024,
    specs: [
      { label: "النوع", value: "شتوي" },
      { label: "درجة الحرارة المثالية", value: "أقل من 7°م" },
    ],
    description: "مادة مطاط خاصة تحافظ على مرونتها بالبرودة وتماسك أفضل على الطرق الرطبة أو الزلقة.",
    installNote: "يُنصح بتخزين الإطارات الصيفية بشكل صحيح عند التبديل.",
    related: ["light-ambient-strip", "tpms-sensor"],
  },
  {
    id: "tpms-sensor",
    categoryId: "wheels",
    name: "مستشعر ضغط هواء (TPMS)",
    brandLabel: "Schrader",
    price: 190,
    stockCount: 20,
    hue: 24,
    compatibleModelIds: ["chevrolet-tahoe", "ford-explorer"],
    yearFrom: 2016,
    yearTo: 2024,
    specs: [
      { label: "الوظيفة", value: "قراءة ضغط الإطار لحظياً" },
      { label: "البطارية", value: "غير قابلة للاستبدال، عمر 7-10 سنوات" },
    ],
    description: "مستشعر يراقب ضغط الهواء بكل إطار ويرسل تنبيه فوري عند انخفاضه عن الحد الآمن.",
    installNote: "يتطلب برمجة على نظام السيارة بعد التركيب.",
    related: ["black-alloy-wheels", "sport-tires-19"],
  },

  // ---------- التعليق ----------
  {
    id: "adjustable-coilovers",
    categoryId: "suspension",
    name: "مساعدات رياضية قابلة للتعديل",
    brandLabel: "KW Suspension",
    price: 4200,
    stockCount: 3,
    hue: 205,
    compatibleModelIds: ["bmw-m4", "porsche-911", "lambo-huracan", "porsche-cayenne"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "التعديل", value: "ارتفاع وصلابة قابلين للضبط" },
      { label: "الاستخدام", value: "شارع ومضمار" },
    ],
    description: "طقم مساعدات كامل يتيح ضبط ارتفاع السيارة وصلابة التعليق يدوياً حسب أسلوب القيادة.",
    installNote: "تركيب وضبط زوايا العجلات إلزامي بعد التركيب.",
    related: ["lowering-springs", "rear-sway-bar"],
    popular: true,
  },
  {
    id: "lowering-springs",
    categoryId: "suspension",
    name: "طقم زنبركات خفض",
    brandLabel: "Eibach",
    price: 980,
    stockCount: 7,
    hue: 195,
    compatibleModelIds: ["mb-c-class", "audi-a4"],
    yearFrom: 2016,
    yearTo: 2024,
    specs: [
      { label: "الخفض", value: "من 25 إلى 35 ملم" },
      { label: "التوافق", value: "مع المساعدات الأصلية" },
    ],
    description: "زنبركات تخفض مركز ثقل السيارة وتحسّن التحكم في المنعطفات مع الحفاظ على راحة مقبولة يومياً.",
    installNote: "يُنصح بضبط زوايا العجلات بعد التركيب مباشرة.",
    related: ["adjustable-coilovers", "front-suspension-bushing"],
  },
  {
    id: "front-suspension-bushing",
    categoryId: "suspension",
    name: "جلبة تعليق أمامي (بوش)",
    brandLabel: "Moog",
    price: 95,
    stockCount: 30,
    hue: 84,
    compatibleModelIds: ["toyota-camry", "nissan-altima"],
    yearFrom: 2017,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "مطاط عالي الكثافة" },
      { label: "الوظيفة", value: "تقليل الاهتزاز والصوت" },
    ],
    description: "جلبة تعليق تمتص الاهتزازات وتمنع الأصوات المزعجة الناتجة عن تآكل الجلب الأصلية.",
    installNote: "قطعة اقتصادية شائعة الاستبدال ضمن الصيانة الدورية.",
    related: ["rear-sway-bar", "lowering-springs"],
  },
  {
    id: "rear-sway-bar",
    categoryId: "suspension",
    name: "قضيب موازنة خلفي",
    brandLabel: "Whiteline",
    price: 340,
    stockCount: 11,
    hue: 40,
    compatibleModelIds: ["toyota-land-cruiser", "chevrolet-tahoe", "bmw-x5"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "القطر", value: "أكبر من الأصلي" },
      { label: "الفائدة", value: "تقليل ميلان الجسم بالمنعطفات" },
    ],
    description: "قضيب موازنة أصلب يقلل ميلان جسم السيارة الجانبي عند المنعطفات، خصوصاً في السيارات العالية والدفع الرباعي.",
    installNote: "تركيب مباشر على نقاط التثبيت الأصلية.",
    related: ["front-suspension-bushing", "adjustable-coilovers"],
  },

  // ---------- قطع الأداء ----------
  {
    id: "turbo-upgrade-kit",
    categoryId: "performance",
    name: "طقم شحن تيربو أداء",
    brandLabel: "Garrett",
    price: 6800,
    stockCount: 2,
    hue: 205,
    compatibleModelIds: ["bmw-m4", "audi-a4"],
    yearFrom: 2017,
    yearTo: 2024,
    specs: [
      { label: "زيادة القوة", value: "حتى ٪25 حصان إضافي" },
      { label: "يشمل", value: "تيربو + أنابيب + وصلات" },
    ],
    description: "طقم ترقية شاحن توربيني كامل يرفع القوة الحصانية بشكل ملموس، مخصص للمستخدمين المتقدمين.",
    installNote: "تركيب متخصص إلزامي، ويُنصح بترقية ملف ECU معه.",
    related: ["ecu-remap", "cold-air-intake"],
    popular: true,
  },
  {
    id: "ecu-remap",
    categoryId: "performance",
    name: "وحدة تحكم أداء (ECU ريمابنق)",
    brandLabel: "Cobb Tuning",
    price: 5200,
    stockCount: 3,
    hue: 24,
    compatibleModelIds: ["porsche-911", "mclaren-720s", "ferrari-roma"],
    yearFrom: 2017,
    yearTo: 2024,
    specs: [
      { label: "النوع", value: "برمجة مخصصة قابلة للتعديل" },
      { label: "أوضاع القيادة", value: "شارع / رياضي / مضمار" },
    ],
    description: "إعادة برمجة كمبيوتر المحرك لتحسين استجابة الدواسة والقوة القصوى، مع الحفاظ على موثوقية المحرك.",
    installNote: "يتطلب جلسة ضبط (Dyno tuning) في الورشة.",
    related: ["turbo-upgrade-kit", "cold-air-intake"],
  },
  {
    id: "cold-air-intake",
    categoryId: "performance",
    name: "مدخل هواء بارد رياضي",
    brandLabel: "AEM",
    price: 620,
    stockCount: 9,
    hue: 84,
    compatibleModelIds: ["toyota-corolla", "nissan-sunny", "chevrolet-camaro"],
    yearFrom: 2016,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "ألمنيوم مصقول" },
      { label: "الفائدة", value: "هواء أبرد وأكثف للمحرك" },
    ],
    description: "نظام مدخل هواء بارد يسحب هواءً أبرد من خارج غرفة المحرك، مما يحسّن الاستجابة والصوت الرياضي.",
    installNote: "تركيب سهل نسبياً، يشمل دليل تركيب مصور.",
    related: ["turbo-upgrade-kit", "air-filter-performance"],
  },
  {
    id: "lightweight-wheel-set",
    categoryId: "performance",
    name: "طقم جنط خفيف الوزن (فورجد)",
    brandLabel: "BBS",
    price: 3100,
    stockCount: 4,
    hue: 195,
    compatibleModelIds: ["lambo-huracan", "porsche-macan", "porsche-cayenne"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "التصنيع", value: "فورجد (مطروق)" },
      { label: "الوزن", value: "أخف من الأصلي بـ ٪20" },
    ],
    description: "جنط مطروق خفيف الوزن يقلل الكتلة الدوارة، ما يحسّن التسارع والفرملة واستجابة التوجيه.",
    installNote: "يشمل توازن دقيق ومطابقة عزم صواميل الشركة المصنّعة.",
    related: ["ecu-remap", "turbo-upgrade-kit"],
  },

  // ---------- الخارجية ----------
  {
    id: "sport-front-bumper",
    categoryId: "exterior",
    name: "مصدّة أمامية رياضية",
    brandLabel: "Aftermarket Body Kit",
    price: 1650,
    stockCount: 6,
    hue: 205,
    compatibleModelIds: ["bmw-3-series", "audi-a4"],
    yearFrom: 2016,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "بولي بروبيلين مقوى" },
      { label: "التصميم", value: "فتحات تبريد إضافية" },
    ],
    description: "مصدّة أمامية بتصميم رياضي تمنح مظهراً أكثر عدوانية مع تحسين تدفق الهواء لتبريد المكابح.",
    installNote: "يُنصح بالطلاء بلون السيارة قبل التركيب النهائي.",
    related: ["carbon-mirrors", "rear-spoiler"],
  },
  {
    id: "carbon-mirrors",
    categoryId: "exterior",
    name: "مرايا كاربون فايبر",
    brandLabel: "Carbon Craft",
    price: 2200,
    stockCount: 5,
    hue: 24,
    compatibleModelIds: ["mclaren-720s", "ferrari-488", "lambo-urus"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "كاربون فايبر حقيقي" },
      { label: "الوزن", value: "أخف من الأصلي" },
    ],
    description: "مرايا جانبية من الكاربون الحقيقي تضيف لمسة رياضية فاخرة وتقلل الوزن مقارنة بالمرايا الأصلية.",
    installNote: "تركيب مباشر على قاعدة المرآة الأصلية بدون تعديل.",
    related: ["sport-front-bumper", "rear-spoiler"],
  },
  {
    id: "replacement-hood",
    categoryId: "exterior",
    name: "غطاء محرك (كبوت) بديل",
    brandLabel: "Genuine Replacement",
    price: 890,
    stockCount: 8,
    hue: 40,
    compatibleModelIds: ["toyota-hilux", "ford-f150"],
    yearFrom: 2016,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "صاج معدني" },
      { label: "يشمل", value: "بدون طلاء (يحتاج دهان)" },
    ],
    description: "غطاء محرك بديل مطابق للمقاسات الأصلية، خيار موثوق بعد حوادث أو تلف بالصدأ.",
    installNote: "يتطلب دهان بلون السيارة وتركيب مفصلات جديدة إذا لزم.",
    related: ["sport-front-bumper", "rear-spoiler"],
  },
  {
    id: "rear-spoiler",
    categoryId: "exterior",
    name: "سبويلر خلفي رياضي",
    brandLabel: "Aftermarket Body Kit",
    price: 540,
    stockCount: 10,
    hue: 84,
    compatibleModelIds: ["chevrolet-camaro", "ford-explorer"],
    yearFrom: 2016,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "ABS مقوى" },
      { label: "التركيب", value: "لاصق + براغي" },
    ],
    description: "سبويلر خلفي يضيف حضوراً رياضياً واضحاً للمظهر الخلفي، مع تحسين طفيف للثبات في السرعات العالية.",
    installNote: "يُنصح بالطلاء بلون السيارة قبل التركيب.",
    related: ["carbon-mirrors", "replacement-hood"],
  },

  // ---------- الداخلية ----------
  {
    id: "leather-sport-seats",
    categoryId: "interior",
    name: "طقم مقاعد جلد رياضية",
    brandLabel: "Recaro",
    price: 8500,
    stockCount: 2,
    hue: 205,
    compatibleModelIds: ["bmw-m4", "porsche-911"],
    yearFrom: 2017,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "جلد طبيعي" },
      { label: "الدعم الجانبي", value: "عالي (تصميم رياضي)" },
    ],
    description: "مقاعد رياضية بدعم جانبي قوي مناسبة للقيادة الحماسية، مع جلد طبيعي فاخر يرفع مستوى المقصورة بالكامل.",
    installNote: "تركيب احترافي يشمل مطابقة نظام الوسائد الهوائية الأصلي.",
    related: ["carbon-steering-wheel", "protective-floor-mats"],
    popular: true,
  },
  {
    id: "carbon-steering-wheel",
    categoryId: "interior",
    name: "عجلة قيادة كاربون",
    brandLabel: "Momo",
    price: 2900,
    stockCount: 4,
    hue: 24,
    compatibleModelIds: ["ferrari-roma", "mclaren-720s", "lambo-huracan"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "كاربون فايبر + جلد" },
      { label: "الأزرار", value: "متوافقة مع أوامر عجلة القيادة" },
    ],
    description: "عجلة قيادة رياضية من الكاربون تمنح قبضة أفضل وإحساساً مباشراً أكثر بالطريق.",
    installNote: "تركيب متخصص للحفاظ على وظائف الوسادة الهوائية وأزرار التحكم.",
    related: ["leather-sport-seats", "light-ambient-strip"],
  },
  {
    id: "protective-floor-mats",
    categoryId: "interior",
    name: "أرضيات حماية أصلية",
    brandLabel: "WeatherTech",
    price: 210,
    stockCount: 24,
    hue: 40,
    compatibleModelIds: ["toyota-camry", "toyota-corolla", "nissan-altima"],
    yearFrom: 2017,
    yearTo: 2024,
    specs: [
      { label: "المادة", value: "مطاط مرن مقاوم للماء" },
      { label: "المقاس", value: "مطابق تماماً لأرضية السيارة" },
    ],
    description: "أرضيات حماية مصممة خصيصاً لكل موديل، تحمي فرش السيارة من الأوساخ والرطوبة طوال العمر.",
    installNote: "تركيب مباشر بدون أدوات، قابلة للإزالة والتنظيف.",
    related: ["leather-sport-seats", "carbon-steering-wheel"],
  },
  {
    id: "navigation-screen-update",
    categoryId: "interior",
    name: "شاشة نظام ملاحة (تحديث)",
    brandLabel: "OEM Upgrade",
    price: 1750,
    stockCount: 6,
    hue: 195,
    compatibleModelIds: ["mb-e-class", "audi-a6", "mb-gle"],
    yearFrom: 2016,
    yearTo: 2024,
    specs: [
      { label: "الحجم", value: "أكبر من الشاشة الأصلية" },
      { label: "يشمل", value: "خرائط محدّثة" },
    ],
    description: "ترقية شاشة نظام الملاحة والترفيه لدعم خرائط أحدث وواجهة استخدام أوضح.",
    installNote: "برمجة وتركيب في الورشة، يشمل نقل الإعدادات.",
    related: ["light-ambient-strip", "protective-floor-mats"],
  },

  // ---------- الإضاءة ----------
  {
    id: "led-headlight-kit",
    categoryId: "lighting",
    name: "طقم مصابيح LED أمامية",
    brandLabel: "Philips",
    price: 890,
    stockCount: 14,
    hue: 205,
    compatibleModelIds: ["toyota-land-cruiser", "nissan-patrol", "ford-f150"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "السطوع", value: "أعلى بـ ٪150 من الهالوجين" },
      { label: "العمر", value: "حتى 30,000 ساعة" },
    ],
    description: "طقم تحويل من الهالوجين إلى LED يمنح إضاءة أوضح وأكثر أماناً في القيادة الليلية.",
    installNote: "تركيب مباشر (Plug & Play) بدون تعديل على الأسلاك الأصلية.",
    related: ["sport-fog-lights", "dynamic-tail-light"],
    popular: true,
  },
  {
    id: "sport-fog-lights",
    categoryId: "lighting",
    name: "مصابيح ضباب رياضية",
    brandLabel: "Hella",
    price: 320,
    stockCount: 15,
    hue: 24,
    compatibleModelIds: ["bmw-3-series", "mb-c-class"],
    yearFrom: 2015,
    yearTo: 2024,
    specs: [
      { label: "النوع", value: "LED" },
      { label: "زاوية الإضاءة", value: "واسعة، مخصصة للضباب" },
    ],
    description: "مصابيح ضباب بزاوية إضاءة واسعة ومنخفضة تحسّن الرؤية في الأجواء الضبابية أو المطيرة.",
    installNote: "تركيب في مكان الفتحات الأصلية بالمصدّة.",
    related: ["led-headlight-kit", "dynamic-tail-light"],
  },
  {
    id: "light-ambient-strip",
    categoryId: "lighting",
    name: "شريط إضاءة داخلي أجواء",
    brandLabel: "Ambient Glow",
    price: 260,
    stockCount: 18,
    hue: 84,
    compatibleModelIds: ["tesla-model-3", "tesla-model-y", "audi-q5"],
    yearFrom: 2018,
    yearTo: 2024,
    specs: [
      { label: "الألوان", value: "متعددة قابلة للتحكم" },
      { label: "التحكم", value: "عبر تطبيق أو أزرار" },
    ],
    description: "إضاءة أجواء داخلية تضيف لمسة عصرية للمقصورة مع إمكانية اختيار اللون المفضل حسب المزاج أو الوقت.",
    installNote: "تركيب خلف الديكورات الداخلية، بدون قص أو تعديل دائم.",
    related: ["navigation-screen-update", "carbon-steering-wheel"],
  },
  {
    id: "dynamic-tail-light",
    categoryId: "lighting",
    name: "مصباح خلفي LED ديناميكي",
    brandLabel: "Depo",
    price: 480,
    stockCount: 9,
    hue: 40,
    compatibleModelIds: ["chevrolet-camaro", "ford-explorer"],
    yearFrom: 2016,
    yearTo: 2024,
    specs: [
      { label: "إشارة الانعطاف", value: "متحركة (Sequential)" },
      { label: "التوافق", value: "Plug & Play" },
    ],
    description: "مصباح خلفي بإشارة انعطاف متحركة تمنح مظهراً عصرياً وحضوراً أوضح للسيارات الخلفية.",
    installNote: "تركيب مباشر مكان المصباح الأصلي.",
    related: ["led-headlight-kit", "sport-fog-lights"],
  },
];

// ---------- Helpers ----------

export function getBrandById(id: string): Brand | undefined {
  return brands.find((b) => b.id === id);
}

export function getModelById(id: string): Model | undefined {
  return models.find((m) => m.id === id);
}

export function getModelsByBrand(brandId: string): Model[] {
  return models.filter((m) => m.brandId === brandId);
}

export function getYearsForModel(modelId: string): number[] {
  const model = getModelById(modelId);
  if (!model) return [];
  const years: number[] = [];
  for (let y = model.yearTo; y >= model.yearFrom; y--) years.push(y);
  return years;
}

export function getCategoryById(id: string): PartCategory | undefined {
  return categories.find((c) => c.id === id);
}

export function getPartById(id: string): Part | undefined {
  return parts.find((p) => p.id === id);
}

export function partsByCategory(categoryId: string): Part[] {
  return parts.filter((p) => p.categoryId === categoryId);
}

/** عدد القطع في كل فئة توافق موديل معيّن (بدون اعتبار السنة) — لعرض تقديري */
export function partsCountForModel(modelId: string): number {
  return parts.filter((p) => p.compatibleModelIds.includes(modelId)).length;
}
